<?php

/**
 * @file
 * Contains newtask.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function newtask_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the newtask module.
    case 'help.page.newtask':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function newtask_theme() {
  $theme = [];
  $theme['newtask_entity'] = [
    'render element' => 'elements',
    'file' => 'newtask_entity.page.inc',
    'template' => 'newtask_entity',
  ];
  $theme['newtask_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'newtask_entity.page.inc',
  ];

  $theme['custom_newtask_entity'] = [
      'render element' => 'content',
      'variables' => ['title' => NULL,
      'description' => NULL,
      'card' => 'null',
      'link' => '',
      ],
      'template' => 'custom_newtask_entity',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function newtask_theme_suggestions_newtask_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#newtask_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'newtask_entity__' . $sanitized_view_mode;
  $suggestions[] = 'newtask_entity__' . $entity->bundle();
  $suggestions[] = 'newtask_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'newtask_entity__' . $entity->id();
  $suggestions[] = 'newtask_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
